import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#005243",
          hover: "#003d32",
          container: "#256b5a",
          "on-container": "#a4e9d3",
          fixed: "#abf0db",
          "fixed-dim": "#90d4bf",
          "on-fixed": "#002019",
          "on-fixed-variant": "#005141",
        },
        secondary: {
          DEFAULT: "#166965",
          container: "#a6f0ea",
          "on-container": "#206f6b",
        },
        tertiary: {
          DEFAULT: "#644119",
          container: "#7f582f",
          "on-container": "#ffd3ab",
        },
        surface: {
          DEFAULT: "#f7f9fb",
          dim: "#d8dadc",
          bright: "#f7f9fb",
          "container-lowest": "#ffffff",
          "container-low": "#f2f4f6",
          container: "#eceef0",
          "container-high": "#e6e8ea",
          "container-highest": "#e0e3e5",
          alt: "#ffffff",
        },
        "on-surface": "#191c1e",
        "on-surface-variant": "#3f4945",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        outline: "#6f7975",
        "outline-variant": "#bfc9c4",
        "surface-tint": "#236958",
        success: "#219653",
        danger: "#D34053",
        warning: "#FFA70B",
        info: "#005243",
        critical: "#D34053",
        high: "#FFA70B",
        medium: "#005243",
        low: "#219653",
        inactive: "#bfc9c4",
        // Legacy aliases for existing components
        background: "#f7f9fb",
        boxdark: "#2d3133",
        "boxdark-2": "#1C2434",
        body: "#3f4945",
        bodydark: "#6f7975",
        bodydark1: "#DEE4EE",
        bodydark2: "#6f7975",
        "text-primary": "#191c1e",
        "text-secondary": "#3f4945",
        border: "#bfc9c4",
        stroke: "#bfc9c4",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600", letterSpacing: "-0.01em" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-lg": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "data-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        // Legacy aliases
        "page-title": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "section-title": ["18px", { lineHeight: "1.3", fontWeight: "600" }],
        "metric": ["32px", { lineHeight: "1.1", fontWeight: "700" }],
        "body": ["15px", { lineHeight: "1.5" }],
        "label": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "caption": ["12px", { lineHeight: "1.4" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
        card: "1rem",
        button: "0.5rem",
        input: "0.5rem",
      },
      spacing: {
        card: "24px",
        section: "32px",
      },
      boxShadow: {
        card: "0px 4px 15px 0px rgba(15, 23, 42, 0.08)",
        "card-hover": "0px 6px 20px 0px rgba(15, 23, 42, 0.12)",
        elevated: "0px 4px 15px 0px rgba(15, 23, 42, 0.08)",
      },
    },
  },
  plugins: [],
};
export default config;
